import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { header } from "@/mocks/header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={
          montserrat.className + " bg-line-gradient-bg bg-no-repeat bg-fixed"
        }
      >
        <Header header={header} />
        {children}
      </body>
    </html>
  );
}
